
<?php $this->widget('zii.widgets.CDetailView', array(
	'data'=>$model,
	'attributes'=>array(
		
		'nama_peserta',
		'tempat_lahir',
		'tanggal_lahir',
		'jenis_kelamin',
		'pilihan_pertama',
		'pilihan_kedua',
		'pilihan_ketiga',
		'alamat_lengkap',
		'desa',
		'kecamatan',
		'kabupaten',
		'propinsi',
		'kodepos',
		'telp',
		'hp',
		'email',
		'pesantren',
		'nama_pesantren',
		'tahun_lulus',
		'lama_pendidikan',
		'takhassus',
		'sd',
		'smp',
		'sma',
		'nama_ayah',
		'pendidikan_ayah',
		'pekerjaan_ayah',
		'penghasilan_ayah',
		'nama_ibu',
		'pendidikan_ibu',
		'pekerjaan_ibu',
		'penghasilan_ibu',
		'pelatihan',
		'skill',
		'is_alumni',
		'kampus_tujuan',
		'rencana_studi',
		'created',
	),
)); ?>
